[package]
name = "b"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"


[[bin]]
name = "b"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.11", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
mini-redis = "0.4"
bytes = "1"
atoi = "2.0.0"
